version: '3.8'

services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_DB: ozon_warehouse_db  # ← БД будет создана автоматически
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-db.sql:/docker-entrypoint-initdb.d/init.sql  # ← SQL скрипт для инициализации
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d ozon_warehouse_db"]
      interval: 10s
      timeout: 5s
      retries: 10

  app:
    build: .
    ports:
      - "5432:5432"
    environment:
      DATABASE_URL: postgresql://postgres:postgres@postgres:5432/ozon_warehouse_db
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - .:/app
    command: >
      sh -c "sleep 15 && uvicorn main:app --host 0.0.0.0 --port 8080"

volumes:
  postgres_data: